# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuestuff', '0002_auto_20160215_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.DateField(null=True)),
                ('outtime', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='current_status',
            field=models.CharField(choices=[(b'IN', b'IN'), (b'OUT', b'OUT')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='discipline',
            field=models.CharField(choices=[(b'Aerospace Engineering', b'Aerospace Engineering'), (b'Animation', b'Animation'), (b'Application Software Centre', b'Application Software Centre'), (b'Applied Geophysics', b'Applied Geophysics'), (b'Applied Statistics and Informatics', b'Applied Statistics and Informatics'), (b'Biomedical Engineering', b'Biomedical Engineering'), (b'Biosciences and Bioengineering', b'Biosciences and Bioengineering'), (b'Biotechnology', b'Biotechnology'), (b'Centre for Aerospace Systems Design and Engineering', b'Centre for Aerospace Systems Design and Engineering'), (b'Centre for Distance Engineering Education Programme', b'Centre for Distance Engineering Education Programme'), (b'Centre for Environmental Science and Engineering', b'Centre for Environmental Science and Engineering'), (b'Centre for Formal Design and Verification of Software', b'Centre for Formal Design and Verification of Software'), (b'Centre for Research in Nanotechnology and Science', b'Centre for Research in Nanotechnology and Science'), (b'Centre for Technology Alternatives for Rural Areas', b'Centre for Technology Alternatives for Rural Areas'), (b'Centre for Urban Science and Engineering', b'Centre for Urban Science and Engineering'), (b'Centre of Studies in Resources Engineering', b'Centre of Studies in Resources Engineering'), (b'Chemical Engineering', b'Chemical Engineering'), (b'Chemistry', b'Chemistry'), (b'Civil Engineering', b'Civil Engineering'), (b'Climate Studies', b'Climate Studies'), (b'Computer Centre', b'Computer Centre'), (b'Computer Science &amp; Engineering', b'Computer Science &amp; Engineering'), (b'Continuing Education Programme', b'Continuing Education Programme'), (b'Corrosion Science and Engineering', b'Corrosion Science and Engineering'), (b'Desai Sethi Centre for Entrepreneurship', b'Desai Sethi Centre for Entrepreneurship'), (b'Earth Sciences', b'Earth Sciences'), (b'Educational Technology', b'Educational Technology'), (b'Electrical Engineering', b'Electrical Engineering'), (b'Energy Science and Engineering', b'Energy Science and Engineering'), (b'Humanities &amp; Social Science', b'Humanities &amp; Social Science'), (b'IITB-Monash Research Academy', b'IITB-Monash Research Academy'), (b'Industrial Design Centre', b'Industrial Design Centre'), (b'Industrial Design Centre', b'Industrial Design Centre'), (b'Industrial Engineering and Operations Research', b'Industrial Engineering and Operations Research'), (b'Industrial Management', b'Industrial Management'), (b'Interaction Design', b'Interaction Design'), (b'Kanwal Rekhi School of Information Technology', b'Kanwal Rekhi School of Information Technology'), (b'Material Science', b'Material Science'), (b'Materials, Manufacturing and Modelling', b'Materials, Manufacturing and Modelling'), (b'Mathematics', b'Mathematics'), (b'Mechanical Engineering', b'Mechanical Engineering'), (b'Metallurgical Engineering &amp; Materials Science', b'Metallurgical Engineering &amp; Materials Science'), (b'Mobility and Vehicle Design', b'Mobility and Vehicle Design'), (b'National Centre for Aerospace Innovation and Research', b'National Centre for Aerospace Innovation and Research'), (b'National Centre for Mathematics', b'National Centre for Mathematics'), (b'Physical Education', b'Physical Education'), (b'Physics', b'Physics'), (b'Physics, Material Science', b'Physics, Material Science'), (b'Preparatory Course', b'Preparatory Course'), (b'Reliability Engineering', b'Reliability Engineering'), (b'Shailesh J. Mehta School of Management', b'Shailesh J. Mehta School of Management'), (b'Sophisticated Analytical Instrument Facility', b'Sophisticated Analytical Instrument Facility'), (b'Systems and Control Engineering', b'Systems and Control Engineering'), (b'Tata Center for Technology and Design', b'Tata Center for Technology and Design'), (b'Visual Communication', b'Visual Communication'), (b'Wadhwani Research Centre for Bioengineering', b'Wadhwani Research Centre for Bioengineering')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduation_year',
            field=models.CharField(choices=[(b'2015', b'2015'), (b'2016', b'2016'), (b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020'), (b'2021', b'2021')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='hostel',
            field=models.CharField(choices=[(b'Hostel 1', b'Hostel 1'), (b'Hostel 2', b'Hostel 2'), (b'Hostel 3', b'Hostel 3'), (b'Hostel 4', b'Hostel 4'), (b'Hostel 5', b'Hostel 5'), (b'Hostel 6', b'Hostel 6'), (b'Hostel 7', b'Hostel 7'), (b'Hostel 8', b'Hostel 8'), (b'Hostel 9', b'Hostel 9'), (b'Hostel 10', b'Hostel 10'), (b'Hostel 11', b'Hostel 11'), (b'Hostel 12', b'Hostel 12'), (b'Hostel 13', b'Hostel 13'), (b'Hostel 14', b'Hostel 14'), (b'Hostel 15', b'Hostel 15'), (b'Tansa', b'Tansa'), (b'QIP', b'QIP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_year',
            field=models.CharField(choices=[(b'2010', b'2010'), (b'2011', b'2011'), (b'2012', b'2012'), (b'2013', b'2013'), (b'2014', b'2014'), (b'2015', b'2015'), (b'2016', b'2016')], max_length=4, null=True),
        ),
    ]
