# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0003_auto_20160215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issuestuff.Log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='intime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='outtime',
            field=models.DateTimeField(null=True),
        ),
    ]
