# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0006_auto_20160215_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.AlterField(
            model_name='member',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuestuff.Log'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[(b'male', b'Male'), (b'female', b'Female'), (b'other', b'Other')], max_length=10, null=True),
        ),
    ]
