# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0007_auto_20160217_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(blank=True, choices=[(b'Bachelor of Technology', b'Bachelor of Technology'), (b'Master of Technology', b'Master of Technology'), (b'B.Tech. + M.Tech. Dual Degree', b'B.Tech. + M.Tech. Dual Degree'), (b'Master of Science', b'Master of Science'), (b'Doctor of Philosophy', b'Doctor of Philosophy'), (b'Bachelor of Design', b'Bachelor of Design'), (b'Master of Design', b'Master of Design'), (b'Master of Philosophy', b'Master of Philosophy'), (b'Master of Management', b'Master of Management'), (b'M.S. (Exit Degree)', b'M.S. (Exit Degree)'), (b'Master of Technology (Exit Degree)', b'Master of Technology (Exit Degree)'), (b'M.Tech. + Ph.D. Dual Degree', b'M.Tech. + Ph.D. Dual Degree'), (b'Preparatory Course', b'Preparatory Course'), (b'Visiting Student', b'Visiting Student'), (b'Master of Philosophy (Exit Degree)', b'Master of Philosophy (Exit Degree)'), (b'Master of Science (Exit Degree)', b'Master of Science (Exit Degree)'), (b'M.Sc. + Ph.D. Dual Degree', b'M.Sc. + Ph.D. Dual Degree'), (b'M.Phil. + Ph.D. Dual Degree', b'M.Phil. + Ph.D. Dual Degree'), (b'Executive MBA', b'Executive MBA'), (b'Four Year BS', b'Four Year BS'), (b'Integrated M.Tech.', b'Integrated M.Tech.'), (b'Master of Science By Research', b'Master of Science By Research'), (b'Two Year M.Sc.', b'Two Year M.Sc.'), (b'Five Year Integrated M.Sc.', b'Five Year Integrated M.Sc.'), (b'D.I.I.T.', b'D.I.I.T.'), (b'D.I.T.T. (Exit Degree)', b'D.I.T.T. (Exit Degree)')], max_length=50, null=True),
        ),
    ]
