# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0008_auto_20160217_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
