# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0009_log_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
