# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuestuff', '0010_auto_20160309_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuinglog',
            name='expectedreturntime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
